default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: sort_event
        name: Sort events on generator
        entry: poetry run python scripts/sort_events.py
        language: system
        pass_filenames: false

      - id: generate
        name: Generate files
        entry: poetry run python generator/generate.py
        language: system
        pass_filenames: false

      - id: update_emit_readme
        name: Generate emit table on readme
        entry: poetry run python scripts/make_readme.py
        language: system
        pass_filenames: false


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black

  -   repo: https://github.com/PyCQA/autoflake
      rev: v2.3.1
      hooks:
      -   id: autoflake

  - repo:  https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.1
    hooks:
      - id: check-github-workflows
      - id: check-dependabot

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
