from bidict import bidict

__all__ = (
    "API_LIMITS_MAX_CONCURRENT_ORDERS",
    "API_LIMITS_MAX_DURATION",
    "API_LIMITS_MAX_ORDER_AMOUNT",
    "API_LIMITS_MIN_DURATION",
    "API_LIMITS_MIN_ORDER_AMOUNT",
    "API_LIMITS_RATE_LIMIT",
    "DEFAULT_ORIGIN",
    "DEFAULT_USER_AGENT",
    "MAX_INT_32",
)
API_LIMITS_MIN_ORDER_AMOUNT = 1
API_LIMITS_MAX_ORDER_AMOUNT = 50_000
API_LIMITS_MIN_DURATION = 5
API_LIMITS_MAX_DURATION = 43_200
API_LIMITS_MAX_CONCURRENT_ORDERS = 10
API_LIMITS_RATE_LIMIT = 100
MAX_INT_32 = 2_147_483_647
DEFAULT_ORIGIN = "https://m.pocketoption.com"
DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:143.0) Gecko/20100101 Firefox/143.0"
